export const AUTH_USER = 'AUTH_USER';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const SIGN_UP_LOADING = 'SIGN_UP_LOADING';
export const USER_INFO_LOADING = 'USER_INFO_LOADING';

export const TEST_INFO_LIST_SET = 'TEST_INFO_LIST_SET';
export const TEST_INFO_LIST_LOADING = 'TEST_INFO_LIST_LOADING';
export const TEST_INFO_LIST_ERROR = 'TEST_INFO_LIST_ERROR';
export const TEST_INFO_SET = 'TEST_INFO_SET';
export const TEST_INFO_LOADING = 'TEST_INFO_LOADING';
export const TEST_INFO_ERROR = 'TEST_INFO_ERROR';
