export const AUTH_USER = 'AUTH_USER';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const SIGN_UP_LOADING = 'SIGN_UP_LOADING';
export const USER_INFO_LOADING = 'USER_INFO_LOADING';

export const TEST_INFO_LIST_SET = 'TEST_INFO_LIST_SET';
export const TEST_INFO_LIST_LOADING = 'TEST_INFO_LIST_LOADING';
export const TEST_INFO_LIST_ERROR = 'TEST_INFO_LIST_ERROR';
export const TEST_INFO_SET = 'TEST_INFO_SET';
export const TEST_INFO_LOADING = 'TEST_INFO_LOADING';
export const TEST_INFO_ERROR = 'TEST_INFO_ERROR';

export const TEST_SET = 'TEST_SET';
export const TEST_START_LOADING = 'TEST_START_LOADING';
export const TEST_START_ERROR = 'TEST_START_ERROR';
export const SET_SELECTED_ANSWERS = 'SET_SELECTED_ANSWERS';
export const TEST_SUBMIT_LOADING = 'TEST_SUBMIT_LOADING';
export const TEST_SUBMIT_ERROR = 'TEST_SUBMIT_ERROR';
export const TEST_CANCEL_LOADING = 'TEST_CANCEL_LOADING';
export const TEST_CANCEL_ERROR = 'TEST_CANCEL_ERROR';

export const UPDATE_RESULT_LIST = 'UPDATE_RESULT_LIST';
export const RESULT_LIST_LOADING = 'RESULT_LIST_LOADING';
export const RESULT_LIST_ERROR = 'RESULT_LIST_ERROR';
export const UPDATE_USER_RESULT_LIST = 'UPDATE_USER_RESULT_LIST';
export const USER_RESULT_LIST_LOADING = 'USER_RESULT_LIST_LOADING';
export const USER_RESULT_LIST_ERROR = 'USER_RESULT_LIST_ERROR';


export const RESULT_STATUS_LOADING = 'RESULT_STATUS_LOADING';
export const RESULT_STATUS_ERROR = 'RESULT_STATUS_ERROR';
